theme: jekyll-theme-minimal
title: Hector22472's homepage
description: Bookmark this to keep an eye on my project updates and reference this website in order to create others
that would be useful like linking my github project repository in my resume.
